name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: xu-cheng/latex-action@25080975331dc4fc8e6f1af55788e00f84f51fff # v4
        with:
          latexmk_use_xelatex: true
          root_file: resume.tex
      - name: Set timestamp
        id: timestamp
        run: echo "version=$(date +'%Y.%m.%d-%H%M%S')" >> "$GITHUB_OUTPUT"
      - name: Create Release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2
        with:
          tag_name: v${{ steps.timestamp.outputs.version }}
          name: Resume ${{ steps.timestamp.outputs.version }}
          files: resume.pdf
